# -*- coding: utf-8 -*-
"""ETL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jrJyH5vxWyVVnH7SKIXDbu9eSpAPltFv
"""

from google.colab import drive

# Mount drive
drive.mount('/content/gdrive')

"""# Retrieve Flex Queries"""

run '/content/gdrive/Shareddrives/ETL/colab_notebooks/reporting/0. Fetch reports from IBKR.ipynb'

"""# Rename files in batch folder"""

run '/content/gdrive/Shareddrives/ETL/colab_notebooks/reporting/1. Rename batch files.ipynb'

"""# Sort files into respective folders"""

# Add revision for existing file in folder

run '/content/gdrive/Shareddrives/ETL/colab_notebooks/reporting/2. Sort batch files into respective folders.ipynb'

"""# Run Clients ETL"""

run '/content/gdrive/Shareddrives/ETL/colab_notebooks/reporting/3. IBKR Clients.ipynb'

"""# Run General ETL"""

run '/content/gdrive/Shareddrives/ETL/colab_notebooks/reporting/4. Reporting Procedures.ipynb'

"""# Upload resources to DB"""

run '/content/gdrive/Shareddrives/ETL/sandbox/reporting/Add resources to database.ipynb'