name: Upload Agreements and Disclosures

on:
  schedule:
    - cron: '0 13 * * *'   # Every day at 1 PM UTC (7:00 AM CST)
  workflow_dispatch:        # Manual trigger

jobs:
  upload_agreements_and_disclosures:
    runs-on: ubuntu-latest
    steps:
      # 1 ─────────────────────────────────────────────────────────
      - name: Request access token
        id: token
        run: |
          response=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -d '{"token":"${{ secrets.AUTHENTICATION_TOKEN }}","scopes":"all"}' \
            https://api.agmtechnology.com/token)

          http_status=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')

          echo "http_status=$http_status" >> "$GITHUB_OUTPUT"
          echo "body=$body" >> "$GITHUB_OUTPUT"

          if [ "$http_status" != "200" ]; then
            echo "Token request failed with status $http_status"
            exit 1
          fi

          access_token=$(echo "$body" | jq -r '.access_token')
          if [ "$access_token" = "null" ] || [ -z "$access_token" ]; then
            echo "access_token not found in response"
            exit 1
          fi
          echo "access_token=$access_token" >> "$GITHUB_OUTPUT"

      # 2 ─────────────────────────────────────────────────────────
      - name: Upload agreements and disclosures
        id: upload
        run: |
          status=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer ${{ steps.token.outputs.access_token }}" \
            -X POST https://api.agmtechnology.com/accounts/documents)

          echo "http_status=$status" >> "$GITHUB_OUTPUT"

          if [ "$status" != "200" ]; then
            echo "Automatic agreements and disclosures upload request failed with status $status"
            exit 1
          fi

      # 3 ─────────────────────────────────────────────────────────
      - name: Summarise results
        run: |
          {
            echo "## Agreements & Disclosures upload summary :clipboard:"
            echo ""
            echo "| Action | HTTP status |"
            echo "| ------ | ----------- |"
            echo "| Token request | \`${{ steps.token.outputs.http_status }}\` |"
            echo "| Agreements upload | \`${{ steps.upload.outputs.http_status }}\` |"
          } >> "$GITHUB_STEP_SUMMARY"

      # 4 (Optional) ──────────────────────────────────────────────
      # - name: Upload raw responses
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: agreements-upload-raw-responses
      #     path: |
      #       ${{ runner.temp }}/token-response.json
      #       ${{ runner.temp }}/agreements-upload-response.json