name: Daily Cloud Run Refresh

on:
  schedule:
    - cron: '0 7 * * *'  # Runs daily at 7 AM UTC (1:00 AM CST)
  workflow_dispatch:        # Manual trigger

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (if needed)
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_KEY }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: agm-datalake

      - name: Force redeploy existing image
        run: |
          gcloud run deploy agm-api \
            --image $(gcloud run services describe agm-api \
              --platform managed \
              --region us-central1 \
              --format 'value(spec.template.spec.containers[0].image)') \
            --region us-central1 \
            --platform managed \
            --quiet

  notify-success:
    needs: redeploy
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send success email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "✅ Daily Cloud Run Refresh SUCCEEDED"
          to: aa@agmtechnology.com
          from: aa@agmtechnology.com
          body: |
            The Daily Cloud Run Refresh workflow completed successfully 🎉

            Repo: ${{ github.repository }}
            Branch: ${{ github.ref }}
            Run URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  notify-failure:
    needs: redeploy
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send failure email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚨 Daily Cloud Run Refresh FAILED"
          to: aa@agmtechnology.com
          from: aa@agmtechnology.com
          body: |
            The Daily Cloud Run Refresh workflow failed ❌

            Repo: ${{ github.repository }}
            Branch: ${{ github.ref }}
            Run URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}