name: Daily Pending Tasks & Leads Summary

on:
  schedule:
    # Every day at 3 PM UTC (9:00 AM CST)
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  fetch-summary:
    runs-on: ubuntu-latest
    outputs:
      tasks: ${{ steps.fetch.outputs.pending_tasks }}
    steps:
      - name: Request token and fetch tasks
        id: fetch
        uses: Wandalen/wretry.action@v2
        with:
          command: |
            # ─────────────────────────────────────────────────────────────
            # 1. Fetch access token (same mechanism as ETL / other jobs)
            response=$(curl -s -w "\n%{http_code}" -X POST \
              -H "Content-Type: application/json" \
              -d '{"token":"all"}' \
              https://api.agmtechnology.com/token)

            http_status=$(echo "$response" | tail -n1)
            body=$(echo "$response" | sed '$d')

            if [ "$http_status" != "200" ]; then
              echo "Token request failed with status $http_status" >&2
              exit 1
            fi

            access_token=$(echo "$body" | jq -r '.access_token')
            if [ "$access_token" = "null" ] || [ -z "$access_token" ]; then
              echo "access_token not found in response" >&2
              exit 1
            fi

            # ─────────────────────────────────────────────────────────────
            # 2. Fetch Pending Tasks
            response=$(curl -s -w "\n%{http_code}" -X GET \
              -H "Authorization: Bearer $access_token" \
              https://api.agmtechnology.com/pending_tasks/read)
            http_status=$(echo "$response" | tail -n1)
            tasks_body=$(echo "$response" | sed '$d')
            if [ "$http_status" != "200" ]; then
              echo "Fetching pending tasks failed with status $http_status" >&2
              exit 1
            fi

            # Extract plain list of pending task descriptions (one per line)
            pending_tasks=$(echo "$tasks_body" | jq -r '.pending_tasks[] | .description')
            # Debug: print raw JSON for inspection
            echo "==== Raw Pending Tasks JSON ===="
            echo "$tasks_body"
            echo "==============================="

            echo "==== Pending Tasks (plain text) ===="
            echo "$pending_tasks"
            echo "==============================="

            # ─────────────────────────────────────────────────────────────
            # 4. Pass plain text lists to next job via step outputs
            printf "pending_tasks<<EOF\n%s\nEOF\n" "$pending_tasks" >> "$GITHUB_OUTPUT"
            
          attempt_limit: 24     # Retry up to 24 times (10-min interval) like other jobs
          attempt_delay: 600000 # 10-minute pause (ms)
          
      - name: Log fetched results
        run: |
          echo "Pending Tasks (plain text):"
          echo "${{ steps.fetch.outputs.pending_tasks }}"

  notify:
    needs: fetch-summary
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Prepare email body
        id: prep_email
        run: |
          SUMMARY_DATE=$(date -u +"%Y-%m-%d %H:%M UTC")
          printf "body<<EOF\n" >> "$GITHUB_OUTPUT"
          printf "Hello AGM team,\n\n" >> "$GITHUB_OUTPUT"
          printf "Here is the daily summary as of $SUMMARY_DATE:\n\n" >> "$GITHUB_OUTPUT"
          printf "Pending Tasks:\n\n" >> "$GITHUB_OUTPUT"
          printf "%s\n\n" "${{ needs.fetch-summary.outputs.tasks }}" >> "$GITHUB_OUTPUT"
          printf "Have a great day!\n" >> "$GITHUB_OUTPUT"
          printf "EOF\n" >> "$GITHUB_OUTPUT"

      - name: Send daily summary email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "📬 Daily Pending Tasks Summary"
          to: aa@agmtechnology.com,cr@agmtechnology.com
          from: aa@agmtechnology.com
          body: ${{ steps.prep_email.outputs.body }}

  notify-failure:
    needs: fetch-summary
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send failure email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚨 Daily Summary Workflow FAILED"
          to: aa@agmtechnology.com,cr@agmtechnology.com
          from: aa@agmtechnology.com
          body: |
            The daily pending tasks summary workflow failed. Please review the workflow logs for details.
